-- Gamlish DBMS Lab · MySQL schema
-- Database: gamlish_dbms
-- Import in phpMyAdmin or run in DBeaver / MySQL Workbench.
-- Column names match the project proposal (User_ID, Level_ID, ...).

CREATE DATABASE IF NOT EXISTS gamlish_dbms
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE gamlish_dbms;

CREATE TABLE Users (
  User_ID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(150) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Role ENUM('student', 'admin') NOT NULL DEFAULT 'student',
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (User_ID),
  UNIQUE KEY UQ_Users_Email (Email)
);

CREATE TABLE Levels (
  Level_ID INT NOT NULL AUTO_INCREMENT,
  Level_Number INT NOT NULL,
  Title VARCHAR(150) NOT NULL,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Level_ID),
  UNIQUE KEY UQ_Levels_Number (Level_Number)
);

CREATE TABLE Lessons (
  Lesson_ID INT NOT NULL AUTO_INCREMENT,
  Level_ID INT NOT NULL,
  Title VARCHAR(150) NOT NULL,
  Video_URL VARCHAR(500) NOT NULL,
  Lesson_Content TEXT NOT NULL,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Lesson_ID),
  CONSTRAINT FK_Lessons_Level
    FOREIGN KEY (Level_ID) REFERENCES Levels (Level_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE QuizQuestions (
  Question_ID INT NOT NULL AUTO_INCREMENT,
  Lesson_ID INT NOT NULL,
  Question TEXT NOT NULL,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Question_ID),
  CONSTRAINT FK_Questions_Lesson
    FOREIGN KEY (Lesson_ID) REFERENCES Lessons (Lesson_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE QuizOptions (
  Option_ID INT NOT NULL AUTO_INCREMENT,
  Question_ID INT NOT NULL,
  Option_Text VARCHAR(255) NOT NULL,
  Is_Correct TINYINT(1) NOT NULL DEFAULT 0,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Option_ID),
  CONSTRAINT FK_Options_Question
    FOREIGN KEY (Question_ID) REFERENCES QuizQuestions (Question_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE UserProgress (
  Progress_ID INT NOT NULL AUTO_INCREMENT,
  User_ID INT NOT NULL,
  Lesson_ID INT NOT NULL,
  Completed TINYINT(1) NOT NULL DEFAULT 0,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Progress_ID),
  UNIQUE KEY UQ_Progress_User_Lesson (User_ID, Lesson_ID),
  CONSTRAINT FK_Progress_User
    FOREIGN KEY (User_ID) REFERENCES Users (User_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT FK_Progress_Lesson
    FOREIGN KEY (Lesson_ID) REFERENCES Lessons (Lesson_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE QuizAttempts (
  Attempt_ID INT NOT NULL AUTO_INCREMENT,
  User_ID INT NOT NULL,
  Question_ID INT NOT NULL,
  Selected_Option INT NOT NULL,
  Score INT NOT NULL,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Attempt_ID),
  UNIQUE KEY UQ_Attempt_User_Question (User_ID, Question_ID),
  CONSTRAINT FK_Attempts_User
    FOREIGN KEY (User_ID) REFERENCES Users (User_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT FK_Attempts_Question
    FOREIGN KEY (Question_ID) REFERENCES QuizQuestions (Question_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT FK_Attempts_Option
    FOREIGN KEY (Selected_Option) REFERENCES QuizOptions (Option_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);
